version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - echo Entered the install phase...
      - apt update
      - apt -y upgrade
      - apt install -y python3-pip
      - apt install build-essential libssl-dev libffi-dev python3-dev
      - apt install -y python3-venv

    finally:
      - echo This always runs even if the update or install command fails 
  pre_build:
    commands:
      - echo Entered the pre_build phase...
      - python3 -m venv test_venv
      - . test_venv/bin/activate
      - pip install --upgrade pip
      - pip install -r requirements.txt
    finally:
      - echo This always runs even if the login command fails 
  build:
    commands:
      - echo Entered the build phase...
      - echo Build started on `date`
      - python -m src.train_new_logistic
    finally:
      - echo This always runs even if the install command fails
  post_build:
    commands:
      - echo Entered the post_build phase...
      - echo Build completed on `date`